config/routes.rb
Rails.application.routes.draw do
  resource :dashboard, only: [:show]

  authenticated :user, lambda { |user| user.has_role?(:admin) } do
    root to: 'admins/dashboards#show'
  end

  authenticated :user do
    root to: 'dashboards#show'
  end

  root to: 'welcome#index'
  get 'welcome/index'

  resources :redemptions, only: :create

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :deeds, only: :create

  namespace :admins do
    resource :dashboard, only: [:show]
    resources :redemptions, only: [:index, :update]
    resources 'prizes', only: [:new, :create, :edit, :update]
    resources 'stations', only: [:new, :create]
    resources 'users', only: [:index] do
      resources :strikes, only: :create
    end
    resources 'admins', only: [:index, :new, :create, :destroy]
  end

  namespace :api do
    namespace :geojson do
      namespace :v1 do
        resources 'stations', only: :index
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if record.errors.any? %>
  <div id="error_explanation">
    <h3>Please fix the following errors:</h3>
    <ul>
      <% record.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<ul id="flash_messages">
  <% flash_filtered_for_display.each do |type, message| %>
    <li class="flash-message <%= type %>">
      <%= message %>
      <button type="button">
        <%= fa_icon 'close' %>
      </button>
    </li>
  <% end %>
</ul>

app/views/shared/_navigation.html.erb
<nav id="app_bar" data-turbolinks-permanent>
  <%= link_to root_path, class: 'logo' do %>
    <%= image_tag 'tree.svg' %>
    <span>Green Steps</span>
  <% end %>

  <%= fa_icon('navicon', class: 'menu_toggler') if user_signed_in? %>
</nav>

<% if user_signed_in? %>
  <div id="nav_drawer_container" data-turbolinks-permanent>
    <nav id="nav_drawer">
      <% if current_user.has_role?(:admin) %>
        <%= link_to t('.user_dashboard'), dashboard_path %>
      <% end %>
      <%= link_to edit_user_registration_path do %>
        <%= fa_icon 'user-circle' %>
        Profile
      <% end %>
      <%= button_to destroy_user_session_path, method: :delete do %>
        <%= fa_icon 'sign-out' %>
        Log out
      <% end %>
      <div class="bottom_links">
        <%= link_to 'https://www.greenstepschatt.com/volunteer/' do %>
          <%= fa_icon 'envelope' %>
          Contact Us
        <% end %>
        <%= link_to "/documents/terms.pdf", target: "_blank" do %>
          <%= fa_icon 'info-circle' %>
          Terms
        <% end %>
      </div>
    </nav>
  </div>
<% end %>

app/views/shared/_prize_button.html.erb
<%= link_to prize_path(prize.id) do %>
  <button class="prize">
    <p><%= prize.title %></p>
    <p><%= "#{prize.cost}pts" %></p>
  </button>
<% end %>

app/views/shared/_update_flash.js.erb
oldFlash = $('#flash_messages')
newFlash = $("<%= j render 'shared/flash' %>")
newFlash.hide()
oldFlash.slideUp()
oldFlash.replaceWith(newFlash)
newFlash.slideDown()
new Greensteps.Dismissable('.flash-message button')

app/views/shared/update_flash.js.erb
<%= render 'update_flash' %>