config/routes.rb
Rails.application.routes.draw do
  resource :dashboard, only: [:show]

  authenticated :user, lambda { |user| user.has_role?(:admin) } do
    root to: 'admins/dashboards#show'
  end

  authenticated :user do
    root to: 'dashboards#show'
  end

  root to: 'welcome#index'
  get 'welcome/index'

  resources :redemptions, only: :create

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :deeds, only: :create

  namespace :admins do
    resource :dashboard, only: [:show]
    resources :redemptions, only: [:index, :update]
    resources 'prizes', only: [:new, :create, :edit, :update]
    resources 'stations', only: [:new, :create]
    resources 'users', only: [:index] do
      resources :strikes, only: :create
    end
    resources 'admins', only: [:index, :new, :create, :destroy]
  end

  namespace :api do
    namespace :geojson do
      namespace :v1 do
        resources 'stations', only: :index
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  has_many :deeds, dependent: :destroy
  has_many :redemptions, dependent: :destroy
  has_many :strikes, dependent: :destroy

  scope :soft_deleted, -> { where.not(deleted_at: nil) }

  # TODO: We definitely need to do some refactoring in here. One idea I had was
  #       to make a scorecard model that is essentially a cache of point
  #       calculations.

  def self.by_total_points(direction = 'DESC')
    with_total_trash_bags.order("total_trash_bags #{direction}")
  end

  def self.with_total_trash_bags
    select <<~SQL
      users.*,
      (
        SELECT COALESCE(SUM(trash_bags), 0) FROM deeds
        WHERE user_id = users.id
      ) AS total_trash_bags
    SQL
  end

  def self.order_by(attribute, direction = 'ASC')
    if column_names.include? attribute.to_s
      order("#{attribute} #{direction}")
    else
      send("by_#{attribute}", direction)
    end
  end

  def total_points
    deeds.total_trash_bags
  end

  def redeemed_points
    redemptions.total_cost
  end

  def unredeemed_points
    total_points - redeemed_points
  end

  def points_redeemed_this_month
    redemptions.this_month.total_cost
  end

  def available_points
    [unredeemed_points, (30 - points_redeemed_this_month)].min
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  def soft_delete
    update(deleted_at: Time.zone.now)
  end

  def active_for_authentication?
    super && deleted_at.blank? && strikes.count < 3
  end

  def inactive_message
    if deleted_at.present?
      :account_deleted
    elsif strikes.count >= 3
      :deactivated_by_admin
    else
      super
    end
  end

  def send_devise_notification(mailer_method_name, *args)
    devise_mailer.send(mailer_method_name, self, *args).deliver_later
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < BaseController
    # TODO: this causing N+1 queries that Bullet is not detecting
    expose :users, :sort_and_paginate_users

    def index; end

    private

    def sort_column
      if %w[email total_points].include?(params['column'])
        params['column']
      else
        'total_points'
      end
    end

    def sort_direction
      if %w[ASC DESC].include?(params['direction'])
        params['direction']
      else
        default_sort_direction
      end
    end

    helper_method :sort_column, :sort_direction

    def default_sort_direction
      sort_column == 'total_points' ? 'DESC' : 'ASC'
    end

    def sort_and_paginate_users
      User.order_by(sort_column, sort_direction).page(params[:page])
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    def create
      super do
        if resource.new_record? &&
           User.soft_deleted.exists?(email: sign_up_params[:email])
          flash[:alert] = t('.account_deleted')
          redirect_back(fallback_location: root_path) && return
        end
      end
    end

    def destroy
      resource.soft_delete
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      set_flash_message! :notice, :destroyed
      respond_with_navigational(resource) do
        redirect_to after_sign_out_path_for(resource_name)
      end
    end
  end
end

app/views/admins/users/index.html.erb
<h1><%= t('.header') %></h1>

<%= paginate users %>

<table class="users">
  <tr>
    <th class="email">
      <%= link_to_sort_by 'email' %>
    </th>
    <th class="total_points">
      <%= link_to_sort_by 'total_points' %>
    </th>
    <th class="redeemed_points">
      <%= t('.redeemed_points') %>
    </th>
    <th class="points_redeemed_this_month">
      <%= t('.points_redeemed_this_month') %>
    </th>
    <th class="strikes">
      <%= t('.strikes') %>
    </th>
    <th class="strike_button">
    </th>
  </tr>
  <% users.each do |user| %>
    <tr class="user" id="user_<%= user.id %>">
      <td class="email">
        <%= user.email %>
      </td>
      <td class="total_points">
        <%= user.total_points %>
      </td>
      <td class="redeemed_points">
        <%= user.redeemed_points %>
      </td>
      <td class="points_redeemed_this_month">
        <%= user.points_redeemed_this_month %>
      </td>
      <td class="strikes">
        <%= user.strikes.size %>
      </td>
      <td class="strike_button">
        <%= button_to t('.strike'), admins_user_strikes_path(user) %>
      </td>
    </tr>
  <% end %>
</table>