config/routes.rb
Rails.application.routes.draw do
  resource :dashboard, only: [:show]

  authenticated :user, lambda { |user| user.has_role?(:admin) } do
    root to: 'admins/dashboards#show'
  end

  authenticated :user do
    root to: 'dashboards#show'
  end

  root to: 'welcome#index'
  get 'welcome/index'

  resources :redemptions, only: :create

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :deeds, only: :create

  namespace :admins do
    resource :dashboard, only: [:show]
    resources :redemptions, only: [:index, :update]
    resources 'prizes', only: [:new, :create, :edit, :update]
    resources 'stations', only: [:new, :create]
    resources 'users', only: [:index] do
      resources :strikes, only: :create
    end
    resources 'admins', only: [:index, :new, :create, :destroy]
  end

  namespace :api do
    namespace :geojson do
      namespace :v1 do
        resources 'stations', only: :index
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/admins/destroy.js.erb
$(".admins li:contains('<%= j(admin.email) %>')").remove()
<%= render 'shared/update_flash' %>

app/views/admins/admins/index.html.erb
<h2><%= t('.header') %></h2>

<ul class="admins">
  <% admins.each do |admin| %>
    <li>
      <%= link_to admins_admin_path(admin), class: 'delete_admin', remote: true, method: :delete do %>
        <%= fa_icon('minus') %>
      <% end %>
      <%= admin.email %>
    </li>
  <% end %>
</ul>

<%= link_to new_admins_admin_path, class: 'new_admin' do %>
  <%= fa_icon('plus') %>
<% end %>

app/views/admins/admins/new.html.erb
<h2><%= t('.header') %></h2>
<%= form_with model: [:admins, admin], id: 'new_admin' do |f| %>
  <%= render 'shared/errors', record: admin %>

  <%= f.label :email %>
  <%= f.email_field :email, required: true %>

  <%= f.submit %>
<% end %>